name: XRAI
channels:
  - defaults
dependencies:
  - ca-certificates=2023.08.22=haa95532_0
  - openssl=3.0.10=h2bbff1b_2
  - pip=23.2.1=py39haa95532_0
  - python=3.9.18=h1aa4202_0
  - setuptools=68.0.0=py39haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - tzdata=2023c=h04d1e81_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.38.4=py39haa95532_0
  - pip:
      - absl-py==1.4.0
      - aif360==0.5.0
      - alibi==0.9.4
      - alibi-detect==0.11.4
      - ansi2html==1.8.0
      - anyio==4.0.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - astunparse==1.6.3
      - async-lru==2.0.4
      - attrs==23.1.0
      - autoviz==0.1.730
      - babel==2.12.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - blackboxauditing==0.1.54
      - bleach==6.0.0
      - blis==0.7.10
      - bokeh==2.4.3
      - brotli==1.1.0
      - build==1.0.3
      - cachetools==5.3.1
      - catalogue==2.0.9
      - certifi==2023.7.22
      - cffi==1.15.1
      - charset-normalizer==3.2.0
      - chart-studio==1.1.0
      - click==8.1.7
      - cloudpickle==2.2.1
      - colorama==0.4.6
      - colorcet==3.0.1
      - colour==0.1.5
      - combo==0.1.3
      - comm==0.1.4
      - confection==0.1.3
      - contourpy==1.1.1
      - cycler==0.11.0
      - cymem==2.0.8
      - dalex==1.6.0
      - dash==2.13.0
      - dash-bootstrap-components==1.3.1
      - dash-colorscales==0.0.4
      - dash-core-components==2.0.0
      - dash-daq==0.5.0
      - dash-html-components==2.0.0
      - dash-mantine-components==0.12.1
      - dash-table==5.0.0
      - debugpy==1.8.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dice-ml==0.10
      - dill==0.3.7
      - distro==1.8.0
      - dm-tree==0.1.8
      - dtale==3.5.0
      - dtreeviz==2.2.2
      - econml==0.14.1
      - emoji==2.8.0
      - entrypoints==0.4
      - erroranalysis==0.5.2
      - et-xmlfile==1.1.0
      - evidently==0.4.5
      - exceptiongroup==1.1.3
      - fairlearn==0.9.0
      - fastapi==0.98.0
      - fastapi-utils==0.2.1
      - fastjsonschema==2.18.0
      - filelock==3.12.4
      - flask==2.2.5
      - flask-compress==1.14
      - flask-ngrok==0.0.25
      - flatbuffers==23.5.26
      - fonttools==4.42.1
      - fqdn==1.5.1
      - fsspec==2023.9.1
      - future==0.18.3
      - gast==0.4.0
      - google-auth==2.23.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - gpytorch==1.11
      - greenlet==2.0.2
      - grpcio==1.58.0
      - h11==0.14.0
      - h5py==3.9.0
      - holoviews==1.14.9
      - htmlmin==0.1.12
      - huggingface-hub==0.17.2
      - hvplot==0.7.3
      - idna==3.4
      - imagehash==4.3.1
      - imageio==2.31.3
      - importlib-metadata==6.8.0
      - importlib-resources==6.0.1
      - iniconfig==2.0.0
      - interpret-community==0.30.0
      - interpret-core==0.4.3
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - iterative-telemetry==0.0.8
      - itsdangerous==2.1.2
      - jaxtyping==0.2.21
      - jedi==0.19.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - jupyter==1.0.0
      - jupyter-client==7.4.9
      - jupyter-console==6.4.4
      - jupyter-core==5.3.1
      - jupyter-events==0.7.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.7.3
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.6
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.24.0
      - jupyterlab-widgets==3.0.9
      - kaleido==0.2.1
      - keras==2.13.1
      - kiwisolver==1.4.5
      - langcodes==3.3.0
      - libclang==16.0.6
      - lightgbm==4.1.0
      - linear-operator==0.5.2
      - llvmlite==0.38.1
      - lz4==4.3.2
      - mapie==0.7.0
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.2
      - matplotlib==3.6.3
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - missingno==0.5.2
      - mistune==3.0.1
      - ml-wrappers==0.5.2
      - mpmath==1.3.0
      - multimethod==1.9.1
      - murmurhash==1.0.10
      - nbclient==0.8.0
      - nbconvert==7.8.0
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - netcal==1.3.5
      - networkx==2.5
      - nltk==3.8.1
      - notebook==7.0.3
      - notebook-shim==0.2.3
      - numba==0.55.2
      - numpy==1.22.4
      - oauthlib==3.2.2
      - opencv-python==4.8.0.76
      - openpyxl==3.1.2
      - opt-einsum==3.3.0
      - overrides==7.4.0
      - oyaml==1.0
      - packaging==23.1
      - pandas-dq==1.28
      - pandas-profiling==3.6.6
      - pandocfilters==1.5.0
      - panel==0.14.4
      - param==1.13.0
      - parso==0.8.3
      - pathy==0.10.2
      - patsy==0.5.3
      - phik==0.12.3
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pip-tools==7.3.0
      - platformdirs==3.10.0
      - plotly==5.17.0
      - pluggy==1.3.0
      - preshed==3.0.9
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - protobuf==4.24.3
      - psutil==5.9.5
      - py4j==0.10.9.7
      - pyamg==5.0.1
      - pyarrow==13.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pyct==0.5.0
      - pydantic==1.10.2
      - pygments==2.16.1
      - pyod==1.1.0
      - pyparsing==3.1.1
      - pyproject-hooks==1.0.0
      - pyro-api==0.1.2
      - pyro-ppl==1.8.6
      - pyspark==3.4.1
      - pytest==7.4.2
      - python-dateutil==2.8.2
      - python-graphviz==0.20.1
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pyviz-comms==3.0.0
      - pywavelets==1.4.1
      - pywin32==306
      - pywinpty==2.0.11
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qii-tool==0.1.3
      - qtconsole==5.4.4
      - qtpy==2.4.0
      - raiutils==0.4.1
      - referencing==0.30.2
      - regex==2023.8.8
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - responsibleai==0.30.0
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.5.3
      - rpds-py==0.10.3
      - rsa==4.9
      - safetensors==0.3.3
      - scikit-image==0.19.3
      - scikit-learn==1.1.3
      - scipy==1.9.3
      - seaborn==0.12.2
      - semver==2.13.0
      - send2trash==1.8.2
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - shap==0.42.1
      - six==1.16.0
      - slicer==0.0.7
      - smart-open==6.4.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - spacy==3.6.1
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - spacy-lookups-data==1.0.5
      - sparse==0.14.0
      - sqlalchemy==1.4.49
      - squarify==0.4.3
      - srsly==2.4.7
      - starlette==0.27.0
      - strsimpy==0.2.1
      - suod==0.0.9
      - sweetviz==2.2.1
      - sympy==1.12
      - tangled-up-in-unicode==0.2.0
      - tenacity==8.2.3
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - tensorflow==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-intel==2.13.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - tensorflow-probability==0.21.0
      - termcolor==2.3.0
      - terminado==0.17.1
      - textblob==0.17.1
      - thinc==8.1.12
      - threadpoolctl==3.2.0
      - tifffile==2023.9.18
      - tikzplotlib==0.9.8
      - tinycss2==1.2.1
      - tokenizers==0.13.3
      - toml==0.10.2
      - tomli==2.0.1
      - torch==2.0.1
      - torchvision==0.15.2
      - tornado==6.3.3
      - tqdm==4.64.1
      - traitlets==5.10.0
      - transformers==4.33.2
      - typeguard==2.13.3
      - typer==0.9.0
      - typing-extensions==4.1.1
      - uncertainty-toolbox==0.1.1
      - uri-template==1.3.0
      - urllib3==1.26.16
      - uvicorn==0.23.2
      - visions==0.7.5
      - waitress==2.1.2
      - wasabi==1.1.2
      - watchdog==3.0.0
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.3
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.9
      - wordcloud==1.9.2
      - wrapt==1.15.0
      - wtforms==3.0.1
      - xarray==2023.8.0
      - xgboost==2.0.0
      - xlrd==2.0.1
      - ydata-profiling==4.1.2
      - yellowbrick==1.5
      - zipp==3.17.0
prefix: C:\Users\Joshua\anaconda3\envs\XRAI
